# Generated by Django 3.2.9 on 2022-01-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='owner',
            new_name='host',
        ),
    ]
