# Generated by Django 3.2.9 on 2022-01-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePages', '0004_auto_20211227_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
