# Generated by Django 3.2.9 on 2022-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePages', '0005_alter_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
