# Generated by Django 2.2 on 2021-12-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePages', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
