# Generated by Django 2.2.24 on 2021-12-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='featured_picture',
            field=models.ImageField(blank=True, default='project.jpg', null=True, upload_to=''),
        ),
    ]
