# Generated by Django 2.2.24 on 2022-01-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20220113_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='applicant',
            field=models.ManyToManyField(blank=True, null=True, to='assignment.Applicant'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='assignment.Tag'),
        ),
    ]
