# Generated by Django 2.2.24 on 2022-01-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20220113_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='assignment.Tag'),
        ),
    ]
