# Generated by Django 2.2.24 on 2021-12-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20211229_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='applicant',
            field=models.ManyToManyField(to='assignment.Applicant'),
        ),
    ]
