# Generated by Django 2.2.24 on 2022-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20220113_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
