# Generated by Django 2.2.24 on 2021-11-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20211123_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
