# Generated by Django 2.2.24 on 2022-01-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20220113_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='tags',
            field=models.ManyToManyField(null=True, to='assignment.Tag'),
        ),
    ]
