# Generated by Django 2.2.24 on 2021-12-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20211229_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='last_name',
        ),
    ]
