# Generated by Django 2.2.24 on 2022-01-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20220113_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='tags',
            field=models.ManyToManyField(to='assignment.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
