# Generated by Django 3.2.9 on 2022-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20220111_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='applicant',
            field=models.ManyToManyField(to='assignment.Applicant'),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='tags',
        ),
        migrations.AddField(
            model_name='assignment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='assignment.Tag'),
        ),
    ]
