# Generated by Django 3.2.9 on 2021-12-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20211210_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='tags',
        ),
        migrations.AddField(
            model_name='assignment',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='assignment.Tag'),
        ),
    ]
