# Generated by Django 3.2.9 on 2022-01-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20220111_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment'),
        ),
    ]
