# Generated by Django 3.2.9 on 2022-01-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_auto_20220112_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.location'),
        ),
    ]
